export enum Coins {
    BTC="btc",
    LTC="ltc",
    DOGE="doge",
    FIO="fio",
    STELLAR="stellar",
    XRP="xrp",
    ETH="eth",
    BNB="bnb",
    MATIC="matic",
    GRS="groestlcoin",
    ONE="harmony",
    CRS="cronos",
    VET="vechain",
    SOLANA= 'solana',
    TEZOS= 'tezos',
    AVAX= 'avax',
    XD= 'xdc',
    KCC= 'kcc',
    OKC= 'okx',
    BSC= 'bsc',
}



export enum CoinIds {
    BTC=0,
    LTC=2,
    DOGE=3,
    FIO=235,
    STELLAR=148,
    XRP=144,
    ETH=60,
    BNB=714,
    MATIC=60,
    GRS=17,
    ONE=60,
    CRS=60,
    VET=60,
    SOLANA= 501,
    TEZOS= 1729,
    AVAX= 60,
    XD= 60,
    KCC= 60,
    OKC= 60,
    BSC= 60,
}