export const NotImplementedError = 'no implementation method';
export const NewAddressError = 'generate address error';
export const ValidAddressError = 'valid address error';
export const SignTxError = 'sign tx error';
export const SignMsgError = 'sign message error';
export const UnsupportedCoinError = 'unsupported currency';
export const GenPrivateKeyError = 'generate private key error';
export const GenMnemonicError = 'generate mnemonic error';
export const InvalidChainError = 'invalid chain';
export const PriorityFeeError = 'prioriy fee is required for current chain';
export const DerivePathError = 'derive hdPath error';
export const InvalidAmount = 'invalid amount';
export const NetworkNotSupported = 'network not supported'
export const CoinNotSupported = 'coin not supported'
export const InvalidAddress = 'invalid address';
export const InvalidContractAddress = 'invalid token contract address';
export const InvalidMnemonic = 'invalid mnemonic';
export const GetMpcRawTransactionError = 'get mpc raw transaction error';
export const GetMpcTransactionError = 'get mpc transaction error';
export const GetHardwareRawTransactionError =
    'get hardware raw transaction error';
export const GetHardwareSignedTransactionError =
    'get hardware signed transaction error';
export const CannotGetNonce = 'Cannot get nonce';
export const InvalidTokenContract = 'invalid token contract';
export const GetHardWareMessageHashError = 'get hardware message hash error';
export const MPCAesKeyMissError = 'mpc get aes key error';
export const MPCStepError = 'mpc step error';
export const MPCShakeHandsError = 'mpc shake hands error';
export const EcdsaSetupError = 'ecdsa setup error';
export const EcdsaStep1Error = 'ecdsa step1 error';
export const EcdsaStep2Error = 'ecdsa step2 error';
export const EcdsaStep3Error = 'ecdsa step3 error';
export const Ed25519SetupError = 'ed25519 setup error';
export const Ed25519Step1Error = 'ed25519 step1 error';
export const Ed25519Step2Error = 'ed25519 step2 error';
export const Ed25519Step3Error = 'ed25519 step3 error';
export const SignMsgSetupError = 'sign message setup error';
export const SignMsgStep3Error = 'sign message step3 error';
export const CalcTxHashError = 'calculate tx hash error';
export const HardwareDerivePubKeyError = 'derive sub pub key error';
export const GetPayLoadError = 'get payload error';
export const validSignedTransactionError = 'valid signed transaction error';
export const EstimateFeeError = 'estimate fee error';
